// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type {
  AuthControllerRegisterData,
  AuthControllerRegisterResponses,
  AuthControllerLoginData,
  AuthControllerLoginResponses,
  AuthControllerVerifyEmailData,
  AuthControllerVerifyEmailResponses,
  AuthControllerResendVerificationData,
  AuthControllerResendVerificationResponses,
  AuthControllerForgotPasswordData,
  AuthControllerForgotPasswordResponses,
  AuthControllerResetPasswordData,
  AuthControllerResetPasswordResponses,
  AuthControllerGetProfileData,
  AuthControllerGetProfileResponses,
  AuthControllerRefreshTokenData,
  AuthControllerRefreshTokenResponses,
  UserControllerGetProfileData,
  UserControllerGetProfileResponses,
  UserControllerFindAllData,
  UserControllerFindAllResponses,
  UserControllerFindAllForLoggedInUserData,
  UserControllerFindAllForLoggedInUserResponses,
  UserControllerAssignRoleData,
  UserControllerAssignRoleResponses,
  UserControllerGetAllRolesData,
  UserControllerGetAllRolesResponses,
  UserControllerRegisterSingleUserData,
  UserControllerRegisterSingleUserResponses,
  UserControllerBulkCreateData,
  UserControllerBulkCreateResponses,
  UserControllerGetAllPermissionsData,
  UserControllerGetAllPermissionsResponses,
  ProgramControllerFindAllData,
  ProgramControllerFindAllResponses,
  ProgramControllerCreateData,
  ProgramControllerCreateResponses,
  ProgramControllerRemoveData,
  ProgramControllerRemoveResponses,
  ProgramControllerFindOneData,
  ProgramControllerFindOneResponses,
  ProgramControllerUpdateData,
  ProgramControllerUpdateResponses,
  ProgramControllerFindWorkflowsByProgramData,
  ProgramControllerFindWorkflowsByProgramResponses,
  ProgramControllerAddWorkflowToProgramData,
  ProgramControllerAddWorkflowToProgramResponses,
  ProgramControllerGetAllProgramsForUserData,
  ProgramControllerGetAllProgramsForUserResponses,
  ProgramControllerAddUsersToProgramData,
  ProgramControllerAddUsersToProgramResponses,
  WorkflowControllerFindAllWorkflowsData,
  WorkflowControllerFindAllWorkflowsResponses,
  WorkflowControllerCreateWorkflowData,
  WorkflowControllerCreateWorkflowResponses,
  WorkflowControllerSearchWorkflowsData,
  WorkflowControllerSearchWorkflowsResponses,
  WorkflowControllerFindWorkflowByIdData,
  WorkflowControllerFindWorkflowByIdResponses,
  WorkflowControllerArchiveWorkflowData,
  WorkflowControllerArchiveWorkflowResponses,
  WorkflowControllerAssignUsersToWorkflowData,
  WorkflowControllerAssignUsersToWorkflowResponses,
  FieldControllerGetWorkflowFieldsData,
  FieldControllerGetWorkflowFieldsResponses,
  FieldControllerUpsertWorkflowFieldsData,
  FieldControllerUpsertWorkflowFieldsResponses,
  FieldControllerRemoveWorkflowFieldData,
  FieldControllerRemoveWorkflowFieldResponses,
  ConfigurationControllerGetWorkflowConfigurationsData,
  ConfigurationControllerGetWorkflowConfigurationsResponses,
  ConfigurationControllerUpsertWorkflowConfigurationsData,
  ConfigurationControllerUpsertWorkflowConfigurationsResponses,
  ConfigurationControllerRemoveWorkflowConfigurationData,
  ConfigurationControllerRemoveWorkflowConfigurationResponses,
  FieldMappingControllerGetWorkflowFieldMappingsData,
  FieldMappingControllerGetWorkflowFieldMappingsResponses,
  FieldMappingControllerUpsertFieldMappingsData,
  FieldMappingControllerUpsertFieldMappingsResponses,
  CollectorControllerProcessAiData,
  CollectorControllerProcessAiResponses,
  CollectorControllerSubmitDataData,
  CollectorControllerSubmitDataResponses,
  IntegrationControllerTestConnectionData,
  IntegrationControllerTestConnectionResponses,
  IntegrationControllerFetchSchemasData,
  IntegrationControllerFetchSchemasResponses,
  IntegrationControllerGetProgramsData,
  IntegrationControllerGetProgramsResponses,
  IntegrationControllerGetDatasetsData,
  IntegrationControllerGetDatasetsResponses,
  IntegrationControllerGetOrgUnitsData,
  IntegrationControllerGetOrgUnitsResponses,
  ExternalConnectionsControllerFindAllData,
  ExternalConnectionsControllerFindAllResponses,
  ExternalConnectionsControllerCreateData,
  ExternalConnectionsControllerCreateResponses,
  ExternalConnectionsControllerRemoveData,
  ExternalConnectionsControllerRemoveResponses,
  ExternalConnectionsControllerFindOneData,
  ExternalConnectionsControllerFindOneResponses,
  ExternalConnectionsControllerUpdateData,
  ExternalConnectionsControllerUpdateResponses,
} from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Register a new user
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerRegisterData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerRegisterResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Login an existing user
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerLoginData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerLoginResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Verify a user's email address
 */
export const authControllerVerifyEmail = <ThrowOnError extends boolean = false>(
  options: Options<AuthControllerVerifyEmailData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerVerifyEmailResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/verify-email',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Resend the email verification link
 */
export const authControllerResendVerification = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerResendVerificationData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerResendVerificationResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/resend-verification',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Request a password reset link
 */
export const authControllerForgotPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerForgotPasswordData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerForgotPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/forgot-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Reset a user's password
 */
export const authControllerResetPassword = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthControllerResetPasswordData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    AuthControllerResetPasswordResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/reset-password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get the profile of the currently authenticated user
 */
export const authControllerGetProfile = <ThrowOnError extends boolean = false>(
  options?: Options<AuthControllerGetProfileData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    AuthControllerGetProfileResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/profile',
    ...options,
  });
};

/**
 * Refresh authentication token
 * Generates a new access token using a valid refresh token.
 * Requires valid JWT authentication.
 */
export const authControllerRefreshToken = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<AuthControllerRefreshTokenData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    AuthControllerRefreshTokenResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/auth/refresh',
    ...options,
  });
};

export const userControllerGetProfile = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetProfileData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    UserControllerGetProfileResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/profile',
    ...options,
  });
};

export const userControllerFindAll = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerFindAllData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    UserControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/all',
    ...options,
  });
};

export const userControllerFindAllForLoggedInUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UserControllerFindAllForLoggedInUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    UserControllerFindAllForLoggedInUserResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users',
    ...options,
  });
};

export const userControllerAssignRole = <ThrowOnError extends boolean = false>(
  options: Options<UserControllerAssignRoleData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    UserControllerAssignRoleResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/{id}/roles/{roleName}',
    ...options,
  });
};

export const userControllerGetAllRoles = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerGetAllRolesData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    UserControllerGetAllRolesResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/roles',
    ...options,
  });
};

export const userControllerRegisterSingleUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UserControllerRegisterSingleUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    UserControllerRegisterSingleUserResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/single-register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const userControllerBulkCreate = <ThrowOnError extends boolean = false>(
  options?: Options<UserControllerBulkCreateData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).post<
    UserControllerBulkCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/bulk/create',
    ...options,
  });
};

export const userControllerGetAllPermissions = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<UserControllerGetAllPermissionsData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    UserControllerGetAllPermissionsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/users/permissions',
    ...options,
  });
};

/**
 * Get all programs with pagination
 */
export const programControllerFindAll = <ThrowOnError extends boolean = false>(
  options: Options<ProgramControllerFindAllData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ProgramControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs',
    ...options,
  });
};

/**
 * Create a new program
 */
export const programControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<ProgramControllerCreateData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ProgramControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Delete a specific program by ID
 */
export const programControllerRemove = <ThrowOnError extends boolean = false>(
  options: Options<ProgramControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    ProgramControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{id}',
    ...options,
  });
};

/**
 * Get a specific program by ID
 */
export const programControllerFindOne = <ThrowOnError extends boolean = false>(
  options: Options<ProgramControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ProgramControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{id}',
    ...options,
  });
};

/**
 * Update a specific program by ID
 */
export const programControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<ProgramControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    ProgramControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Get all workflows associated with a specific program
 */
export const programControllerFindWorkflowsByProgram = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProgramControllerFindWorkflowsByProgramData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ProgramControllerFindWorkflowsByProgramResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{id}/workflows',
    ...options,
  });
};

/**
 * Associate multiple workflows with a specific program
 */
export const programControllerAddWorkflowToProgram = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProgramControllerAddWorkflowToProgramData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ProgramControllerAddWorkflowToProgramResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{id}/workflows',
    ...options,
  });
};

/**
 * Get all programs associated with a specific user
 */
export const programControllerGetAllProgramsForUser = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProgramControllerGetAllProgramsForUserData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ProgramControllerGetAllProgramsForUserResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{userId}/users',
    ...options,
  });
};

/**
 * Assign multiple users to a specific program
 */
export const programControllerAddUsersToProgram = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ProgramControllerAddUsersToProgramData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ProgramControllerAddUsersToProgramResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/programs/{id}/users',
    ...options,
  });
};

export const workflowControllerFindAllWorkflows = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WorkflowControllerFindAllWorkflowsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    WorkflowControllerFindAllWorkflowsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows',
    ...options,
  });
};

export const workflowControllerCreateWorkflow = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WorkflowControllerCreateWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    WorkflowControllerCreateWorkflowResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const workflowControllerSearchWorkflows = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WorkflowControllerSearchWorkflowsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    WorkflowControllerSearchWorkflowsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/search',
    ...options,
  });
};

export const workflowControllerFindWorkflowById = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WorkflowControllerFindWorkflowByIdData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    WorkflowControllerFindWorkflowByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}',
    ...options,
  });
};

export const workflowControllerArchiveWorkflow = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WorkflowControllerArchiveWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    WorkflowControllerArchiveWorkflowResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}',
    ...options,
  });
};

export const workflowControllerAssignUsersToWorkflow = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WorkflowControllerAssignUsersToWorkflowData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    WorkflowControllerAssignUsersToWorkflowResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/users',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const fieldControllerGetWorkflowFields = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FieldControllerGetWorkflowFieldsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    FieldControllerGetWorkflowFieldsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/fields',
    ...options,
  });
};

export const fieldControllerUpsertWorkflowFields = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FieldControllerUpsertWorkflowFieldsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    FieldControllerUpsertWorkflowFieldsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/fields/upsert',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const fieldControllerRemoveWorkflowField = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FieldControllerRemoveWorkflowFieldData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    FieldControllerRemoveWorkflowFieldResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/fields/{fieldId}',
    ...options,
  });
};

export const configurationControllerGetWorkflowConfigurations = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConfigurationControllerGetWorkflowConfigurationsData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    ConfigurationControllerGetWorkflowConfigurationsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/configurations',
    ...options,
  });
};

export const configurationControllerUpsertWorkflowConfigurations = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConfigurationControllerUpsertWorkflowConfigurationsData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).put<
    ConfigurationControllerUpsertWorkflowConfigurationsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/configurations',
    ...options,
  });
};

export const configurationControllerRemoveWorkflowConfiguration = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ConfigurationControllerRemoveWorkflowConfigurationData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).delete<
    ConfigurationControllerRemoveWorkflowConfigurationResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/configurations/{configId}',
    ...options,
  });
};

export const fieldMappingControllerGetWorkflowFieldMappings = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    FieldMappingControllerGetWorkflowFieldMappingsData,
    ThrowOnError
  >
) => {
  return (options.client ?? _heyApiClient).get<
    FieldMappingControllerGetWorkflowFieldMappingsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/field-mappings',
    ...options,
  });
};

export const fieldMappingControllerUpsertFieldMappings = <
  ThrowOnError extends boolean = false,
>(
  options: Options<FieldMappingControllerUpsertFieldMappingsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).put<
    FieldMappingControllerUpsertFieldMappingsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/workflows/{workflowId}/field-mappings/upsert',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const collectorControllerProcessAi = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CollectorControllerProcessAiData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CollectorControllerProcessAiResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/collector/process-ai',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const collectorControllerSubmitData = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CollectorControllerSubmitDataData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    CollectorControllerSubmitDataResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/collector/submit',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Confirm connection
 */
export const integrationControllerTestConnection = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IntegrationControllerTestConnectionData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    IntegrationControllerTestConnectionResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/integration/test-connection',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

/**
 * Fetch schemas
 */
export const integrationControllerFetchSchemas = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IntegrationControllerFetchSchemasData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    IntegrationControllerFetchSchemasResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/integration/{connectionId}/schemas',
    ...options,
  });
};

export const integrationControllerGetPrograms = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IntegrationControllerGetProgramsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    IntegrationControllerGetProgramsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/integration/dhis2/programs/{connectionId}',
    ...options,
  });
};

export const integrationControllerGetDatasets = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IntegrationControllerGetDatasetsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    IntegrationControllerGetDatasetsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/integration/dhis2/datasets/{connectionId}',
    ...options,
  });
};

export const integrationControllerGetOrgUnits = <
  ThrowOnError extends boolean = false,
>(
  options: Options<IntegrationControllerGetOrgUnitsData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    IntegrationControllerGetOrgUnitsResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/integration/dhis2/{connectionId}/orgunits',
    ...options,
  });
};

export const externalConnectionsControllerFindAll = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ExternalConnectionsControllerFindAllData, ThrowOnError>
) => {
  return (options?.client ?? _heyApiClient).get<
    ExternalConnectionsControllerFindAllResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/external-connections',
    ...options,
  });
};

export const externalConnectionsControllerCreate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExternalConnectionsControllerCreateData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).post<
    ExternalConnectionsControllerCreateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/external-connections',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
};

export const externalConnectionsControllerRemove = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExternalConnectionsControllerRemoveData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).delete<
    ExternalConnectionsControllerRemoveResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/external-connections/{id}',
    ...options,
  });
};

export const externalConnectionsControllerFindOne = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExternalConnectionsControllerFindOneData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).get<
    ExternalConnectionsControllerFindOneResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/external-connections/{id}',
    ...options,
  });
};

export const externalConnectionsControllerUpdate = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ExternalConnectionsControllerUpdateData, ThrowOnError>
) => {
  return (options.client ?? _heyApiClient).patch<
    ExternalConnectionsControllerUpdateResponses,
    unknown,
    ThrowOnError
  >({
    url: '/api/v1/external-connections/{id}',
    ...options,
  });
};
