// This file is auto-generated by @hey-api/openapi-ts

export type RegisterDto = {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
};

export type RegisterResponseDto = {
  message: string;
  userId: string;
};

export type LoginDto = {
  email: string;
  password: string;
};

export type AuthResponse = {
  message?: string;
  accessToken: string;
  user: {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
    isEmailVerified?: boolean;
    roles: Array<string>;
    permissions: Array<string>;
    createdAt?: string;
  };
};

export type VerifyEmailDto = {
  token: string;
};

export type ResendVerificationDto = {
  email: string;
};

export type ForgotPasswordDto = {
  email: string;
};

export type ResetPasswordDto = {
  token: string;
  newPassword: string;
};

export type FieldMapping = {
  id: string;
  workflow: Workflow;
  workflowField: WorkflowField;
  targetType: 'dhis2' | 'postgres';
  target: {
    [key: string]: unknown;
  };
  createdBy: User;
  createdAt: string;
};

export type WorkflowField = {
  id: string;
  workflow: Workflow;
  fieldName: string;
  label: string;
  fieldType:
    | 'text'
    | 'number'
    | 'date'
    | 'datetime'
    | 'select'
    | 'multiselect'
    | 'boolean'
    | 'email'
    | 'phone'
    | 'url'
    | 'textarea';
  options?: Array<string>;
  isRequired: boolean;
  validationRules: {
    [key: string]: unknown;
  };
  aiMapping: {
    [key: string]: unknown;
  };
  displayOrder: number;
  createdBy: User;
  createdAt: string;
  updatedAt: string;
  fieldMappings: Array<FieldMapping>;
};

export type ExternalConnection = {
  id: string;
  name: string;
  type: 'dhis2' | 'postgres';
  configuration: {
    [key: string]: unknown;
  };
  isActive: boolean;
  lastTestedAt?: string;
  testResult?: {
    [key: string]: unknown;
  };
  createdAt: string;
  updatedAt: string;
  workflowConfigurations: WorkflowConfiguration;
  createdBy: User;
};

export type WorkflowConfiguration = {
  id: string;
  workflow: Workflow;
  type: 'dhis2' | 'postgres';
  externalConnection: ExternalConnection;
  configuration: {
    [key: string]: unknown;
  };
  isActive: boolean;
  createdBy: User;
  createdAt: string;
  updatedAt: string;
};

export type Workflow = {
  id: string;
  name: string;
  description: string;
  status: 'active' | 'inactive' | 'archived';
  supportedLanguages: Array<string>;
  enabledModes: Array<'audio' | 'text' | 'form' | 'image'>;
  program: Program;
  workflowFields: Array<WorkflowField>;
  fieldMappings: Array<FieldMapping>;
  workflowConfigurations: Array<WorkflowConfiguration>;
  users: Array<User>;
  createdBy: User;
  version: number;
  createdAt: string;
  updatedAt: string;
};

export type Program = {
  id: string;
  name: string;
  description: string;
  workflows: Array<Workflow>;
  users: Array<User>;
  createdBy: User;
  createdAt: string;
  updatedAt: string;
};

export type AiProcessingLog = {
  id: string;
  user: User;
  workflow: Workflow;
  processingType: 'audio' | 'text' | 'image';
  inputFileIds: Array<string>;
  formSchema: {
    [key: string]: unknown;
  };
  inputText: string;
  mappedOutput: {
    [key: string]: unknown;
  };
  confidenceScore: number;
  processingTimeMs: number;
  aiProvider: string;
  aiModelVersion: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  errorMessage: string;
  metadata: {
    [key: string]: unknown;
  };
  createdAt: string;
  completedAt: string;
};

export type Submission = {
  id: string;
  user: User;
  workflow: Workflow;
  localId: string;
  data: {
    [key: string]: unknown;
  };
  metadata: {
    [key: string]: unknown;
  };
  status:
    | 'pending'
    | 'processing'
    | 'completed'
    | 'failed'
    | 'draft'
    | 'submitted'
    | 'synced'
    | 'archived';
  validationErrors: {
    [key: string]: unknown;
  };
  createdAt: string;
  submittedAt: string;
};

export type User = {
  id: string;
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  isEmailVerified: boolean;
  emailVerificationToken: string;
  resetPasswordToken: string;
  resetPasswordExpires: string;
  forcePasswordReset: boolean;
  roles: Array<Role>;
  programs: Array<Program>;
  workflows: Array<Workflow>;
  isFirstLogin: boolean;
  lastLoginAt: string;
  createdBy?: User;
  createdUsers: Array<User>;
  aiProcessingLogs: Array<AiProcessingLog>;
  submissions: Array<Submission>;
  externalConnections: Array<ExternalConnection>;
  createdAt: string;
  updatedAt: string;
};

export type Permission = {
  id: string;
  name: string;
  description: string;
  resource: string;
  action: string;
  roles: Array<Role>;
};

export type Role = {
  id: string;
  name: string;
  description: string;
  users: Array<User>;
  permissions: Array<Permission>;
};

export type CreateProgramDto = {
  name: string;
  description?: string;
};

export type UpdateProgramDto = {
  [key: string]: unknown;
};

export type AssignUsersToProgramDto = {
  userIds: Array<string>;
};

export type ProgramSummaryDto = {
  id: string;
  name: string;
};

export type ExternalConnectionSummaryDto = {
  id: string;
};

export type WorkflowConfigSummaryDto = {
  id: string;
  name: string;
  type: string;
  isActive: boolean;
  configuration: {
    [key: string]: unknown;
  };
  createdAt: string;
  externalConnection?: ExternalConnectionSummaryDto;
  workflow?: Workflow;
};

export type WorkflowFieldSummaryDto = {
  id: string;
  fieldName: string;
  label: string;
  fieldType: string;
  options: Array<string>;
  isRequired: boolean;
  displayOrder: number;
  createdAt: string;
  updatedAt: string;
};

export type FieldMappingSummaryDto = {
  id: string;
  targetType: string;
  target: {
    [key: string]: unknown;
  };
  createdAt: string;
};

export type UserSummaryDto = {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
};

export type WorkflowResponseDto = {
  id: string;
  name: string;
  description: string;
  status: string;
  supportedLanguages: Array<string>;
  enabledModes: Array<string>;
  version: string;
  createdAt: string;
  updatedAt: string;
  program?: ProgramSummaryDto;
  workflowConfigurations: Array<WorkflowConfigSummaryDto>;
  workflowFields: Array<WorkflowFieldSummaryDto>;
  fieldMappings: Array<FieldMappingSummaryDto>;
  createdBy: UserSummaryDto;
  users: Array<UserSummaryDto>;
};

export type UpdateWorkflowBasicDto = {
  name?: string;
  description?: string;
  supportedLanguages?: Array<string>;
  enabledModes?: Array<'audio' | 'text' | 'form' | 'image'>;
};

export type CreateWorkflowFieldDto = {
  fieldName: string;
  label: string;
  fieldType:
    | 'text'
    | 'number'
    | 'date'
    | 'datetime'
    | 'select'
    | 'multiselect'
    | 'boolean'
    | 'email'
    | 'phone'
    | 'url'
    | 'textarea';
  options?: Array<string>;
  isRequired?: boolean;
  validationRules?: {
    [key: string]: unknown;
  };
  aiMapping?: {
    [key: string]: unknown;
  };
  displayOrder: number;
};

export type CreateWorkflowConfigurationDto = {
  type: 'dhis2' | 'postgres';
  configuration: {
    [key: string]: unknown;
  };
  externalConnectionId: string;
  isActive?: boolean;
};

export type CreateWorkflowDto = {
  programId?: string;
  name: string;
  description: string;
  supportedLanguages?: Array<string>;
  enabledModes: Array<'audio' | 'text' | 'form' | 'image'>;
  workflowFields: Array<CreateWorkflowFieldDto>;
  workflowConfigurations: Array<CreateWorkflowConfigurationDto>;
};

export type AssignUsersDto = {
  userIds: Array<string>;
};

export type Field = {
  id?: string;
  fieldName?: string;
  label?: string;
  fieldType?:
    | 'text'
    | 'number'
    | 'date'
    | 'datetime'
    | 'select'
    | 'multiselect'
    | 'boolean'
    | 'email'
    | 'phone'
    | 'url'
    | 'textarea';
  options?: Array<string>;
  isRequired?: boolean;
  validationRules?: {
    [key: string]: unknown;
  };
  aiMapping?: {
    [key: string]: unknown;
  };
  displayOrder?: number;
};

export type UpsertWorkflowFieldsDto = {
  fields: Array<Field>;
};

export type CreateFieldMappingDto = {
  workflowFieldId: string;
  targetType: 'dhis2' | 'postgres';
  target?: {
    [key: string]: unknown;
  };
};

export type UpsertFieldMappingsDto = {
  fieldMappings: Array<CreateFieldMappingDto>;
};

export type ProcessAiDto = {
  workflowId: string;
  processingType: 'audio' | 'text' | 'image';
  aiProvider?: 'openai' | 'google_vision';
  text?: string;
};

export type SubmitDto = {
  workflowId: string;
  data: {
    [key: string]: unknown;
  };
  metadata: {
    [key: string]: unknown;
  };
  localId?: string;
  aiProcessingLogId?: string;
};

export type ConnectionDto = {
  type: 'dhis2' | 'postgres';
  config: {
    [key: string]: unknown;
  };
};

export type _Object = {
  [key: string]: unknown;
};

export type CreateConnectionDto = {
  name: string;
  type: 'dhis2' | 'postgres';
  configuration: {
    [key: string]: unknown;
  };
};

export type AuthControllerRegisterData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/register';
};

export type AuthControllerRegisterResponses = {
  201: RegisterResponseDto;
};

export type AuthControllerRegisterResponse =
  AuthControllerRegisterResponses[keyof AuthControllerRegisterResponses];

export type AuthControllerLoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type AuthControllerLoginResponses = {
  200: AuthResponse;
};

export type AuthControllerLoginResponse =
  AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerLogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type AuthControllerLogoutResponses = {
  201: unknown;
};

export type AuthControllerVerifyEmailData = {
  body: VerifyEmailDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/verify-email';
};

export type AuthControllerVerifyEmailResponses = {
  200: unknown;
};

export type AuthControllerResendVerificationData = {
  body: ResendVerificationDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/resend-verification';
};

export type AuthControllerResendVerificationResponses = {
  200: unknown;
};

export type AuthControllerForgotPasswordData = {
  body: ForgotPasswordDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/forgot-password';
};

export type AuthControllerForgotPasswordResponses = {
  200: unknown;
};

export type AuthControllerResetPasswordData = {
  body: ResetPasswordDto;
  path?: never;
  query?: never;
  url: '/api/v1/auth/reset-password';
};

export type AuthControllerResetPasswordResponses = {
  200: unknown;
};

export type AuthControllerGetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/profile';
};

export type AuthControllerGetProfileResponses = {
  200: unknown;
};

export type AuthControllerRefreshTokenData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh';
};

export type AuthControllerRefreshTokenResponses = {
  200: AuthResponse;
};

export type AuthControllerRefreshTokenResponse =
  AuthControllerRefreshTokenResponses[keyof AuthControllerRefreshTokenResponses];

export type UserControllerGetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/profile';
};

export type UserControllerGetProfileResponses = {
  200: unknown;
};

export type UserControllerFindAllData = {
  body?: never;
  path?: never;
  query: {
    page: number;
    limit: number;
  };
  url: '/api/v1/users/all';
};

export type UserControllerFindAllResponses = {
  200: unknown;
};

export type UserControllerFindAllForLoggedInUserData = {
  body?: never;
  path?: never;
  query: {
    page: number;
    limit: number;
  };
  url: '/api/v1/users';
};

export type UserControllerFindAllForLoggedInUserResponses = {
  200: unknown;
};

export type UserControllerAssignRoleData = {
  body?: never;
  path: {
    id: string;
    roleName: string;
  };
  query?: never;
  url: '/api/v1/users/{id}/roles/{roleName}';
};

export type UserControllerAssignRoleResponses = {
  201: unknown;
};

export type UserControllerGetAllRolesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/roles';
};

export type UserControllerGetAllRolesResponses = {
  200: unknown;
};

export type UserControllerRegisterSingleUserData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: '/api/v1/users/single-register';
};

export type UserControllerRegisterSingleUserResponses = {
  201: unknown;
};

export type UserControllerBulkCreateData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/bulk/create';
};

export type UserControllerBulkCreateResponses = {
  201: unknown;
};

export type UserControllerGetAllPermissionsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/users/permissions';
};

export type UserControllerGetAllPermissionsResponses = {
  200: Array<Permission>;
};

export type UserControllerGetAllPermissionsResponse =
  UserControllerGetAllPermissionsResponses[keyof UserControllerGetAllPermissionsResponses];

export type ProgramControllerGetProgramsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    userId?: string;
  };
  url: '/api/v1/programs';
};

export type ProgramControllerGetProgramsResponses = {
  200: unknown;
};

export type ProgramControllerCreateData = {
  body: CreateProgramDto;
  path?: never;
  query?: never;
  url: '/api/v1/programs';
};

export type ProgramControllerCreateResponses = {
  201: Program;
};

export type ProgramControllerCreateResponse =
  ProgramControllerCreateResponses[keyof ProgramControllerCreateResponses];

export type ProgramControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/programs/{id}';
};

export type ProgramControllerRemoveResponses = {
  200: unknown;
};

export type ProgramControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/programs/{id}';
};

export type ProgramControllerFindOneResponses = {
  200: Program;
};

export type ProgramControllerFindOneResponse =
  ProgramControllerFindOneResponses[keyof ProgramControllerFindOneResponses];

export type ProgramControllerUpdateData = {
  body: UpdateProgramDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/programs/{id}';
};

export type ProgramControllerUpdateResponses = {
  200: Program;
};

export type ProgramControllerUpdateResponse =
  ProgramControllerUpdateResponses[keyof ProgramControllerUpdateResponses];

export type ProgramControllerFindWorkflowsByProgramData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/programs/{id}/workflows';
};

export type ProgramControllerFindWorkflowsByProgramResponses = {
  200: Array<Workflow>;
};

export type ProgramControllerFindWorkflowsByProgramResponse =
  ProgramControllerFindWorkflowsByProgramResponses[keyof ProgramControllerFindWorkflowsByProgramResponses];

export type ProgramControllerAddWorkflowToProgramData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/programs/{id}/workflows';
};

export type ProgramControllerAddWorkflowToProgramResponses = {
  201: Program;
};

export type ProgramControllerAddWorkflowToProgramResponse =
  ProgramControllerAddWorkflowToProgramResponses[keyof ProgramControllerAddWorkflowToProgramResponses];

export type ProgramControllerGetAllProgramsForUserData = {
  body?: never;
  path: {
    userId: string;
  };
  query?: never;
  url: '/api/v1/programs/{userId}/users';
};

export type ProgramControllerGetAllProgramsForUserResponses = {
  200: unknown;
};

export type ProgramControllerAddUsersToProgramData = {
  body: AssignUsersToProgramDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/programs/{id}/users';
};

export type ProgramControllerAddUsersToProgramResponses = {
  201: Program;
};

export type ProgramControllerAddUsersToProgramResponse =
  ProgramControllerAddUsersToProgramResponses[keyof ProgramControllerAddUsersToProgramResponses];

export type WorkflowControllerGetWorkflowsData = {
  body?: never;
  path?: never;
  query?: {
    userId?: string;
    page?: number;
    limit?: number;
  };
  url: '/api/v1/workflows';
};

export type WorkflowControllerGetWorkflowsResponses = {
  200: unknown;
};

export type WorkflowControllerCreateWorkflowData = {
  body: CreateWorkflowDto;
  path?: never;
  query?: never;
  url: '/api/v1/workflows';
};

export type WorkflowControllerCreateWorkflowResponses = {
  201: Workflow;
};

export type WorkflowControllerCreateWorkflowResponse =
  WorkflowControllerCreateWorkflowResponses[keyof WorkflowControllerCreateWorkflowResponses];

export type WorkflowControllerSearchWorkflowsData = {
  body?: never;
  path?: never;
  query: {
    q: string;
    page: number;
    limit: number;
  };
  url: '/api/v1/workflows/search';
};

export type WorkflowControllerSearchWorkflowsResponses = {
  200: unknown;
};

export type WorkflowControllerFindWorkflowByIdData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}';
};

export type WorkflowControllerFindWorkflowByIdResponses = {
  200: WorkflowResponseDto;
};

export type WorkflowControllerFindWorkflowByIdResponse =
  WorkflowControllerFindWorkflowByIdResponses[keyof WorkflowControllerFindWorkflowByIdResponses];

export type WorkflowControllerArchiveWorkflowData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}';
};

export type WorkflowControllerArchiveWorkflowResponses = {
  200: unknown;
};

export type WorkflowControllerAssignUsersToWorkflowData = {
  body: AssignUsersDto;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/users';
};

export type WorkflowControllerAssignUsersToWorkflowResponses = {
  201: Workflow;
};

export type WorkflowControllerAssignUsersToWorkflowResponse =
  WorkflowControllerAssignUsersToWorkflowResponses[keyof WorkflowControllerAssignUsersToWorkflowResponses];

export type FieldControllerGetWorkflowFieldsData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/fields';
};

export type FieldControllerGetWorkflowFieldsResponses = {
  200: Array<WorkflowField>;
};

export type FieldControllerGetWorkflowFieldsResponse =
  FieldControllerGetWorkflowFieldsResponses[keyof FieldControllerGetWorkflowFieldsResponses];

export type FieldControllerUpsertWorkflowFieldsData = {
  body: UpsertWorkflowFieldsDto;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/fields/upsert';
};

export type FieldControllerUpsertWorkflowFieldsResponses = {
  200: unknown;
};

export type FieldControllerRemoveWorkflowFieldData = {
  body?: never;
  path: {
    fieldId: string;
  };
  query?: never;
  url: '/api/v1/workflows/fields/{fieldId}';
};

export type FieldControllerRemoveWorkflowFieldResponses = {
  200: unknown;
};

export type ConfigurationControllerGetWorkflowConfigurationsData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/configurations';
};

export type ConfigurationControllerGetWorkflowConfigurationsResponses = {
  200: Array<WorkflowConfigSummaryDto>;
};

export type ConfigurationControllerGetWorkflowConfigurationsResponse =
  ConfigurationControllerGetWorkflowConfigurationsResponses[keyof ConfigurationControllerGetWorkflowConfigurationsResponses];

export type ConfigurationControllerUpsertWorkflowConfigurationsData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/configurations';
};

export type ConfigurationControllerUpsertWorkflowConfigurationsResponses = {
  200: Array<WorkflowConfiguration>;
};

export type ConfigurationControllerUpsertWorkflowConfigurationsResponse =
  ConfigurationControllerUpsertWorkflowConfigurationsResponses[keyof ConfigurationControllerUpsertWorkflowConfigurationsResponses];

export type ConfigurationControllerRemoveWorkflowConfigurationData = {
  body?: never;
  path: {
    configId: string;
  };
  query?: never;
  url: '/api/v1/workflows/configurations/{configId}';
};

export type ConfigurationControllerRemoveWorkflowConfigurationResponses = {
  200: unknown;
};

export type FieldMappingControllerGetWorkflowFieldMappingsData = {
  body?: never;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/field-mappings';
};

export type FieldMappingControllerGetWorkflowFieldMappingsResponses = {
  200: Array<FieldMapping>;
};

export type FieldMappingControllerGetWorkflowFieldMappingsResponse =
  FieldMappingControllerGetWorkflowFieldMappingsResponses[keyof FieldMappingControllerGetWorkflowFieldMappingsResponses];

export type FieldMappingControllerUpsertFieldMappingsData = {
  body: UpsertFieldMappingsDto;
  path: {
    workflowId: string;
  };
  query?: never;
  url: '/api/v1/workflows/{workflowId}/field-mappings/upsert';
};

export type FieldMappingControllerUpsertFieldMappingsResponses = {
  200: unknown;
};

export type CollectorControllerProcessAiData = {
  body: ProcessAiDto;
  path?: never;
  query?: never;
  url: '/api/v1/collector/process-ai';
};

export type CollectorControllerProcessAiResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type CollectorControllerProcessAiResponse =
  CollectorControllerProcessAiResponses[keyof CollectorControllerProcessAiResponses];

export type CollectorControllerSubmitDataData = {
  body: SubmitDto;
  path?: never;
  query?: never;
  url: '/api/v1/collector/submit';
};

export type CollectorControllerSubmitDataResponses = {
  201: unknown;
};

export type IntegrationControllerTestConnectionData = {
  body: ConnectionDto;
  path?: never;
  query?: never;
  url: '/api/v1/integration/test-connection';
};

export type IntegrationControllerTestConnectionResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type IntegrationControllerTestConnectionResponse =
  IntegrationControllerTestConnectionResponses[keyof IntegrationControllerTestConnectionResponses];

export type IntegrationControllerFetchSchemasData = {
  body?: never;
  path: {
    connectionId: string;
  };
  query?: {
    id?: string;
    type?: _Object;
  };
  url: '/api/v1/integration/{connectionId}/schemas';
};

export type IntegrationControllerFetchSchemasResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type IntegrationControllerFetchSchemasResponse =
  IntegrationControllerFetchSchemasResponses[keyof IntegrationControllerFetchSchemasResponses];

export type IntegrationControllerGetProgramsData = {
  body?: never;
  path: {
    connectionId: string;
  };
  query: {
    page: number;
    pageSize: number;
  };
  url: '/api/v1/integration/dhis2/programs/{connectionId}';
};

export type IntegrationControllerGetProgramsResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type IntegrationControllerGetProgramsResponse =
  IntegrationControllerGetProgramsResponses[keyof IntegrationControllerGetProgramsResponses];

export type IntegrationControllerGetDatasetsData = {
  body?: never;
  path: {
    connectionId: string;
  };
  query: {
    page: number;
    pageSize: number;
  };
  url: '/api/v1/integration/dhis2/datasets/{connectionId}';
};

export type IntegrationControllerGetDatasetsResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type IntegrationControllerGetDatasetsResponse =
  IntegrationControllerGetDatasetsResponses[keyof IntegrationControllerGetDatasetsResponses];

export type IntegrationControllerGetOrgUnitsData = {
  body?: never;
  path: {
    connectionId: string;
  };
  query: {
    id: string;
    type: _Object;
  };
  url: '/api/v1/integration/dhis2/{connectionId}/orgunits';
};

export type IntegrationControllerGetOrgUnitsResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type IntegrationControllerGetOrgUnitsResponse =
  IntegrationControllerGetOrgUnitsResponses[keyof IntegrationControllerGetOrgUnitsResponses];

export type ExternalConnectionsControllerFindAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/external-connections';
};

export type ExternalConnectionsControllerFindAllResponses = {
  200: Array<ExternalConnection>;
};

export type ExternalConnectionsControllerFindAllResponse =
  ExternalConnectionsControllerFindAllResponses[keyof ExternalConnectionsControllerFindAllResponses];

export type ExternalConnectionsControllerCreateData = {
  body: CreateConnectionDto;
  path?: never;
  query?: never;
  url: '/api/v1/external-connections';
};

export type ExternalConnectionsControllerCreateResponses = {
  201: unknown;
};

export type ExternalConnectionsControllerRemoveData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/external-connections/{id}';
};

export type ExternalConnectionsControllerRemoveResponses = {
  200: unknown;
};

export type ExternalConnectionsControllerFindOneData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/external-connections/{id}';
};

export type ExternalConnectionsControllerFindOneResponses = {
  200: ExternalConnection;
};

export type ExternalConnectionsControllerFindOneResponse =
  ExternalConnectionsControllerFindOneResponses[keyof ExternalConnectionsControllerFindOneResponses];

export type ExternalConnectionsControllerUpdateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/api/v1/external-connections/{id}';
};

export type ExternalConnectionsControllerUpdateResponses = {
  200: ExternalConnection;
};

export type ExternalConnectionsControllerUpdateResponse =
  ExternalConnectionsControllerUpdateResponses[keyof ExternalConnectionsControllerUpdateResponses];

export type ClientOptions = {
  baseUrl: string;
};
